# Form implementation generated from reading ui file 'miau.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(267, 119)
        self.roomNumberLabel = QtWidgets.QLabel(parent=Form)
        self.roomNumberLabel.setGeometry(QtCore.QRect(90, 20, 49, 16))
        self.roomNumberLabel.setObjectName("roomNumberLabel")
        self.cleanStatusLabel = QtWidgets.QLabel(parent=Form)
        self.cleanStatusLabel.setGeometry(QtCore.QRect(130, 80, 49, 16))
        self.cleanStatusLabel.setObjectName("cleanStatusLabel")
        self.checkInOutButton = QtWidgets.QPushButton(parent=Form)
        self.checkInOutButton.setGeometry(QtCore.QRect(30, 50, 75, 24))
        self.checkInOutButton.setObjectName("checkInOutButton")
        self.checkInOutButton.setText("Cazare/Decazare")
        self.cleanedButton = QtWidgets.QPushButton(parent=Form)
        self.cleanedButton.setGeometry(QtCore.QRect(30, 80, 75, 24))
        self.cleanedButton.setObjectName("cleanedButton")
        self.cleanedButton.setText("Curatat camera")
        self.checkInDate = QtWidgets.QLabel(parent=Form)
        self.checkInDate.setGeometry(QtCore.QRect(130, 50, 49, 16))
        self.checkInDate.setObjectName("checkInDate")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.roomNumberLabel.setText(_translate("Form", "TextLabel"))
        self.cleanStatusLabel.setText(_translate("Form", "TextLabel"))
        self.checkInOutButton.setText(_translate("Form", "PushButton"))
        self.cleanedButton.setText(_translate("Form", "PushButton"))
        self.checkInDate.setText(_translate("Form", "TextLabel"))
